const express = require('express');
const cors = require('cors');
const path = require('path');
const swaggerUi = require('swagger-ui-express');
const apiRoutes = require('./routes/apiRoutes');

// Load autogenerated swagger output
let swaggerDocument;
try {
  swaggerDocument = require('./swagger-output.json');
} catch (err) {
  swaggerDocument = {};
}

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());

// Setup Swagger UI
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));

// Routes
app.use('/api', apiRoutes);

// Start Server
app.listen(PORT, () => {
  console.log(`========================================================`);
  console.log(`Server running on http://localhost:${PORT}`);
  console.log(`Swagger documentation: http://localhost:${PORT}/api-docs`);
  console.log(`========================================================`);
});
